# This is how the content of db-secrets.yaml would look if you saved it.
# ENSURE THIS IS NOT COMMITTED TO GIT WITH RAW VALUES.
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: YWRtaW4= # Base64 encoded 'admin'
  DB_PASSWORD: WV9ST0FEX0JBU0U2NF9FTkNPREVEX0RBVEFCQVNFX1BBU1NXT1JE # Base64 encoded 'REPLACE_WITH_YOUR_STRONG_DATABASE_PASSWORD'